/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class formularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formularioPrincipal
     */
    
    public formularioPrincipal() {
        initComponents();
        
        //Se carga la imagen desde el archivo:
        ImageIcon iconoOriginal = 
                new ImageIcon("src\\main\\java\\Presentacion\\imagenes\\logo_avion.jpg");
        
        //Se modifica el tamaño de la imagen:
        Image imagenEscalada = 
                iconoOriginal.getImage().getScaledInstance(100, 300, Image.SCALE_SMOOTH);
        
        ImageIcon iconoRedimensionado = new ImageIcon(imagenEscalada);
        
        //Se establece el icono en la etiqueta:
        etiquetaLogo.setIcon(iconoRedimensionado);
        //Se borra el texto visible de la etiqueta:
        etiquetaLogo.setText("");
        
        //Se obtiene el tamaño de la etiqueta:
        //int ancho = etiquetaLogo.getWidth();
        //int alto = etiquetaLogo.getHeight();
        
        //Se ajusta la imagen al tamaño de la etiqueta:
        //Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        
        //ImageIcon iconoRedimensionado = new ImageIcon(imagenEscalada);
        //Se establece el icono en la etiqueta:
        //etiquetaLogo.setIcon(iconoRedimensionado);
        //etiquetaLogo.setText("");
        //etiquetaLogo.setPreferredSize(new Dimension(100, 100));
        //etiquetaLogo.setSize(100, 100);
        
        ImageIcon iconoOriginalUsuario = new ImageIcon("src\\main\\java\\Presentacion\\imagenes\\logo_usuario.png");
        Image imagenEscaladaUsuario = iconoOriginalUsuario.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        
        ImageIcon iconoRedimensionadoUsuario = new ImageIcon(imagenEscaladaUsuario);
        botonUsuarios.setIcon(iconoRedimensionadoUsuario);
        botonUsuarios.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuarios = new javax.swing.JButton();
        etiquetaLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonUsuarios.setText("Usuarios");

        etiquetaLogo.setText("Logo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JLabel etiquetaLogo;
    // End of variables declaration//GEN-END:variables
}
