/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dominio.Principal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class formularioPrincipal extends javax.swing.JFrame {

    private Principal principal;

    public Principal getPrincipal() {
        return principal;
    }

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    
    public formularioPrincipal(Principal principal) {
        this.principal = principal;
        initComponents();
        
        //Se carga la imagen desde el archivo:
        ImageIcon iconoOriginal = 
                new ImageIcon("src\\main\\java\\Presentacion\\imagenes\\logo_avion.jpg");
        
        //Se modifica el tamaño de la imagen:
        Image imagenEscalada = 
                iconoOriginal.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        
        ImageIcon iconoRedimensionado = new ImageIcon(imagenEscalada);
        
        //Se establece el icono en la etiqueta:
        etiquetaLogo.setIcon(iconoRedimensionado);
        //Se borra el texto visible de la etiqueta:
        etiquetaLogo.setText("");
        
        //Se obtiene el tamaño de la etiqueta:
        //int ancho = etiquetaLogo.getWidth();
        //int alto = etiquetaLogo.getHeight();
        
        //Se ajusta la imagen al tamaño de la etiqueta:
        //Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        
        //ImageIcon iconoRedimensionado = new ImageIcon(imagenEscalada);
        //Se establece el icono en la etiqueta:
        //etiquetaLogo.setIcon(iconoRedimensionado);
        //etiquetaLogo.setText("");
        //etiquetaLogo.setPreferredSize(new Dimension(100, 100));
        //etiquetaLogo.setSize(100, 100);
        
        ImageIcon iconoOriginalUsuario = new ImageIcon("src\\main\\java\\Presentacion\\imagenes\\logo_usuario.png");
        Image imagenEscaladaUsuario = iconoOriginalUsuario.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        
        ImageIcon iconoRedimensionadoUsuario = new ImageIcon(imagenEscaladaUsuario);
        botonUsuarios2.setIcon(iconoRedimensionadoUsuario);
        botonUsuarios2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuarios2 = new javax.swing.JButton();
        etiquetaLogo = new javax.swing.JLabel();
        botonUsuarios = new javax.swing.JButton();
        botonReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonUsuarios2.setText("Usuarios");

        etiquetaLogo.setText("Logo");

        botonUsuarios.setText("Usuarios");
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        botonReservas.setText("Reservas");
        botonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonUsuarios)
                    .addComponent(botonReservas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(botonUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonUsuarios)
                        .addGap(28, 28, 28)
                        .addComponent(botonReservas)
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        formularioUsuarios form = new formularioUsuarios(this.principal);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setVisible(true);
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservasActionPerformed
        formularioReservas form = new formularioReservas(this.principal);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setVisible(true);
    }//GEN-LAST:event_botonReservasActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonReservas;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonUsuarios2;
    private javax.swing.JLabel etiquetaLogo;
    // End of variables declaration//GEN-END:variables
}
